### ISSUE TITLE
Hangs when installing hackwaly.ocaml VS Code extension using the CLI

### ISSUE THREAD

**Issue by gaborigloi** [xapi-project/dev-vm#15]
I also tried it on my dev machine, and it hung there as well. However, adding it manually in VS Code worked fine.

**Comment by Frezzle** [comment]
Turns out it is a known issue in VS Code: https://github.com/Microsoft/vscode/issues/32381

One of the maintainers has said that it's fixed on master and would have been released at the end of August, but it hasn't come out yet; so the next VS Code update should contain the fix (in a week or 2 I'm guessing).
